name: Claim Free Games

on: # When to run this workflow
    push: # When you edit this repo

# Uncomment the below lines to enable manual trigger.

    watch:
        types: [started] # When repo owner stars this repo

    schedule:
        - cron: "0 0 * * *" # Everyday at 00:00 UTC

jobs:
    claim:
        runs-on: ubuntu-latest

        timeout-minutes: 5 # Automatically stop after 5 minutes

        steps:
            - name: Setup repo
              uses: actions/checkout@v2
              with:
                  repository: "Revadike/epicgames-freebies-claimer"

            - name: Setup Node.js
              uses: actions/setup-node@v1

            - name: Install dependencies
              run: yarn

            - name: Hotfix for \#4 # https://github.com/xuac/claim-epic-freebies/issues/4
              run: mkdir .egstore

            - name: Get Epic Freebies
              run: yarn start ${{ secrets.USERNAME }} ${{ secrets.PASSWORD }} 0 ${{ secrets.SECRETKEY }}
